# Generated by Django 4.2.13 on 2026-06-04 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Course Name')),
                ('code', models.CharField(help_text='Unique course code (e.g., CS-2026).', max_length=20, unique=True, verbose_name='Course Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the course in semesters.', verbose_name='Duration (Semesters)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
    ]
