# Generated by Django 4.2.13 on 2026-06-05 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Biometric Confidence'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('BIOMETRIC', 'Biometric')], default='MANUAL', max_length=15, verbose_name='Attendance Source'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Biometric Verification Time'),
        ),
        migrations.CreateModel(
            name='BiometricProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('face_template', models.CharField(max_length=64, verbose_name='Face Template')),
                ('sample_size', models.PositiveIntegerField(default=0, verbose_name='Enrollment Sample Size')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('consent_given_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Consent Given At')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Verified At')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_biometric_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled By')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profile', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Biometric Profile',
                'verbose_name_plural': 'Biometric Profiles',
                'ordering': ['student__roll_number'],
            },
        ),
    ]
